# Generated by Django 4.1.2 on 2022-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
