# Generated by Django 4.1.2 on 2022-11-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_plan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.CharField(max_length=4),
        ),
    ]
