# Generated by Django 4.1.2 on 2022-11-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['id']},
        ),
    ]
