# Generated by Django 4.1.2 on 2022-11-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='is_paid',
            new_name='paid',
        ),
    ]
