# Generated by Django 4.1.2 on 2022-11-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_card_expiry_date'),
        ('subscriptions', '0003_alter_invoice_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.card'),
        ),
    ]
